# Stage 1 — build
FROM node:20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Передаём VITE_API_URL как ENV или берётся из .env
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Stage 2 — nginx
FROM nginx:alpine

# Копируем билд
COPY --from=builder /app/dist /usr/share/nginx/html

# Кастомный конфиг (если нужен)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80