# --- Stage 0: клонируем проект ---
FROM alpine/git as git-clone
ARG GIT_REPO
ARG GIT_BRANCH
RUN git clone --branch ${GIT_BRANCH} --single-branch ${GIT_REPO} /repo

# --- Stage 1: build .NET проект ---
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY --from=git-clone /repo .

COPY ReportPortal.DAL/ReportPortal.DAL.csproj ReportPortal.DAL/
COPY ReportPortal.BLR/ReportPortal.BL.csproj ReportPortal.BLR/
COPY ReportPortal/ReportPortal.csproj ReportPortal/

WORKDIR /src/ReportPortal
RUN dotnet restore

COPY . .

RUN dotnet publish -c Release -o /app/publish

# --- Stage 2: runtime ---
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "ReportPortal.dll"]