# --- Stage 1: Build .NET проект ---
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Копируем проекты
COPY ReportPortal.DAL/ReportPortal.DAL.csproj ReportPortal.DAL/
COPY ReportPortal.BLR/ReportPortal.BL.csproj ReportPortal.BLR/
COPY ReportPortal/ReportPortal.csproj ReportPortal/

# Восстанавливаем зависимости
RUN dotnet restore ReportPortal/ReportPortal.csproj

# Копируем остальные файлы
COPY . .

# Публикуем сборку
WORKDIR /src/ReportPortal
RUN dotnet publish -c Release -o /app/publish

# --- Stage 2: Runtime ---
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "ReportPortal.dll"]