# Используем официальный SDK-образ для сборки
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Копируем все файлы
COPY . ./

# Переходим в директорию веб-проекта
WORKDIR /app/ReportPortal

# Восстанавливаем зависимости и публикуем
RUN dotnet restore
RUN dotnet publish -c Release -o /app/out

# Используем официальный рантайм-образ для запуска
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

# Указываем порт, который будет слушать контейнер
EXPOSE 80

# Стартовая команда
ENTRYPOINT ["dotnet", "ReportPortal.dll"]